version: '2'
services:
  frs_be:
    hostname: frs_be
    container_name: frs_be
    restart: always
    image: frs_be
    privileged: true
    ipc: host
    tty: true
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - '3080:8080'
      - '3022:22'

