version: '2'
services:
  meta_admin:
    hostname: frs_be
    container_name: frs_be
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/zekechin/frs_be
    privileged: true
    ipc: host
    tty: true
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - '8088:8080'
      - '2022:22'

